### ISSUE TITLE
Question about Floppy Discs 3.5

### ISSUE THREAD

**Issue by vico93** [MarbleHoarder/MH-projects#2]
I really like your resourcepack!

I want to ask if you would have interest in do a similar resourcepack but replacing [CC:Tweaked](https://github.com/cc-tweaked/CC-Tweaked)'s [floppy disk](https://www.computercraft.info/wiki/Floppy_Disk) texture/model with similar ones of your resource pack.

**Comment by MarbleHoarder** [comment]
Cerrently I have something like this:
![image](https://github.com/MarbleHoarder/MH-projects/assets/143597241/c2ab646f-fda1-43c7-ba3e-442a707d79de)
or this:
![image](https://github.com/MarbleHoarder/MH-projects/assets/143597241/9f17a9b7-0595-4232-88b7-52cfbf798871)
The black one looks a bit awkward on the second picture due to the way CC:Tweaked handles colour overlays for disks. I could also make is so that the disk's body stays black but the vertical bar in the middle changes colour simmilar to this:
![image](https://github.com/MarbleHoarder/MH-projects/assets/143597241/c10607fd-f4ad-4711-8747-a7c6db5fdf78)

**Comment by vico93** [comment]
This is amazing!

**Comment by MarbleHoarder** [comment]
Sorry for the wait
[CC Reflopped Full.zip](https://github.com/user-attachments/files/16127019/CC.Reflopped.Full.zip)
[CC Reflopped Bar.zip](https://github.com/user-attachments/files/16127020/CC.Reflopped.Bar.zip)
I made two versions, both have some issues, mainly with the black and white colours but they should look fine for the rest of them.
